#file: noinspection SpringBootApplicationYaml
# suppress inspection "SpringBootApplicationProperties" for whole file
# эту настройку лучше не выносить, иначе приложение сначала запустится с другого порта
server:
  port: 8765

spring:
  application:
    name: msm-gateway
  config:
    import: configserver:http://localhost:8888

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

#spring.profiles.active=ssl
